<h3 class="page-title heading heading--smaller blueCapitalized"><?php echo $this->getCheckout()->getStepData("shipping_method", "label"); ?></h3>
<form id="co-shipping-method-form" action="" class="a-center">
    <div id="checkout-shipping-method-load" class="a-left">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <div class="a-center">
            <button type="button" class="btn" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <div>
                <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
                </span>
            </div>
        </div>
        <p class="back-link a-left"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</form>
