<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($_code == 'monetico_multitime'): ?>
        <li class="control">
            <input type="checkbox" name="monetico[multitime_implements]" id="<?php echo $_code ?>_multitime_implements" value="<?php echo Mage::getStoreConfig('payment/monetico_multitime/number_terms') ?>" title="<?php echo $this->__('Payment %s times', Mage::getStoreConfig('payment/monetico_multitime/number_terms')) ?>" class="checkbox" />
            <label for="<?php echo $_code ?>_multitime_implements"><?php echo $this->__('Payment %s times', Mage::getStoreConfig('payment/monetico_multitime/number_terms')) ?></label>
            <input type="hidden" id="<?php echo $_code ?>_nbrech" name="payment[nbrech]" value="1" />
            <script type="text/javascript">
                //<![CDATA[
                var NTChecked<?php echo $_code ?> = function() {
                    var elm = $('<?php echo $_code ?>_multitime_implements');
                    console.log(elm);
                    if (elm.checked) {
                        $('<?php echo $_code ?>_nbrech').value = elm.value;
                    } else {
                        $('<?php echo $_code ?>_nbrech').value = 1;
                    }
                };

                Event.observe($('<?php echo $_code ?>_multitime_implements'), 'click', NTChecked<?php echo $_code ?>);
                NTChecked<?php echo $_code ?>();
                //]]>
            </script>
        </li>
    <?php endif; ?>

    <?php if($_code == "monetico_onetime" || $_code == "monetico_multitime") :?>
        <li>
            <?php echo $this->__('Payment through the CM-CIC service.'); ?>
        </li>
        <li class="logos">
            <div class="payment-method-bank-icon payment_method_monetico_cic"></div>
            <div class="payment-method-bank-icon payment_method_monetico_cm"></div>
        </li>
    <?php elseif ($_code == "monetico_3xcb" || $_code == "monetico_4xcb") : ?>
        <li>
            <?php echo $this->__('Payment through the Cofidis service.'); ?>
        </li>
        <li class="logos">
            <div class="payment-method-bank-icon payment_method_monetico_cofidis"></div>
        </li>
    <?php else : ?>
        <li>
            <?php echo $this->__('Payment through the PayPal service.'); ?>
        </li>
        <li class="logos">
            <div class="payment-method-bank-icon payment_method_monetico_paypal"></div>
        </li>
    <?php endif; ?>
</ul>
