<script type="text/javascript">
    jQuery(document).ready(function($){
        $('#storeLocationList .pager select').each(function(){
            $(this).attr('onchange','updateStoreList(this.value)');
        });
        $('#storeLocationList .pager a').click(function(){
            var url = $(this).attr('href');
            $('#storeLocationList').load(url + '#storeLocationWrap');
            return false;
        })
    })
    function updateStoreList(url){
        jQuery('#storeLocationList').load(url + '#storeLocationWrap');
    }
</script>
