<?php
/*
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
/**
 * Store location list template
 *
 * @category    Plugincompany
 * @package     Plugincompany_Storelocator
 * @author      Milan Simek
 */
?>
<?php
    $helper = Mage::helper('plugincompany_storelocator');
?>
{{#location}}
<div class="loc-name">{{locname}}</div>
<div>{{address}}</div>
<div>{{address2}}</div>
<div style="white-space:nowrap">{{city}}, {{state}} {{postal}}</div>
<div>{{hours1}}</div>
<div>{{hours2}}</div>
<div>{{hours3}}</div>
<div>{{phone}}</div>
{{#if ratingenabled}}
<div class="loc-rating starrr" data-rating='{{rating}}'  data-disabled='true'>{{#displaystars}}{{rating}}{{/displaystars}}</div>
{{/if}}
{{#if web}}
    <div><a href="http://{{web}}" target="_blank"><?php echo $helper->__('Visit website') ?></a></div>
{{/if}}
<div class="loc-web"><a style="" href="{{pageurl}}"><?php echo $helper->__('View store details') ?></a></div>
{{/location}}