<?php
/*
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
/**
 * Store location list template
 *
 * @category    Plugincompany
 * @package     Plugincompany_Storelocator
 * @author      Milan Simek
 */
?>
<?php
    $helper = Mage::helper('plugincompany_storelocator');
?>
{{#location}}
<li data-markerid="{{markerid}}">
	<div class="list-label">{{marker}}</div>
	<div class="list-details">
		<div class="list-content">
			<div class="loc-name">{{locname}}</div>
			<div class="loc-addr">{{address}}</div> 
			<div class="loc-addr2">{{address2}}</div> 
			<div class="loc-addr3">{{city}}, {{state}} {{postal}}</div>
			<div class="loc-phone">{{phone}}</div>
			{{#if ratingenabled}}
			<div class="loc-rating starrr" data-rating='{{rating}}'  data-disabled='true'>{{#displaystars}}{{rating}}{{/displaystars}}</div>
			{{/if}}
            {{#if web}}
                <div class="loc-web"><a href="http://{{web}}" target="_blank"><?php echo $helper->__('Visit website') ?></a></div>
            {{/if}}
            <div class="loc-web"><a href="{{pageurl}}"><?php echo $helper->__("View store details"); ?></a></div>
			{{#if distance}}<div class="loc-dist">{{distance}} {{length}}</div>
			<div class="loc-directions"><a href="http://maps.google.com/maps?saddr={{origin}}&amp;daddr={{address}} {{address2}} {{city}}, {{state}} {{postal}}" target="_blank"><?php echo $helper->__('Directions') ?></a></div>{{/if}}
		</div>
	</div>
</li>
{{/location}}