<?php
/*
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
?>

<?php
    $helper = Mage::helper('plugincompany_storelocator');
?>

<div style="float:left;width:100%;" id="storeLocatorWrapper">

<div class="bh-sl-container">
    <div id="page-header" style="margin-left:5px;">
        <h1><?php echo Mage::getStoreConfig('plugincompany_storelocator/storefinder/findertitle') ?></h1>
        <p class="locatordesc">
            <?php echo Mage::getStoreConfig('plugincompany_storelocator/storefinder/findertext') ?>
        </p>
    </div>
    <div class="bh-sl-form-container">
        <form id="bh-sl-user-location" method="post" action="#">
            <div class="form-input">
                <input placeholder="<?php echo $helper->__('Enter Address or Zip Code'); ?>" type="text" id="bh-sl-address" name="bh-sl-address" autocomplete="off" />
                <button id="bh-sl-submit" type="submit"><?php echo $helper->__('Submit'); ?></button>
            </div>
            <?php if($this->canMaxDistance() == 'true' || $this->canNameFilter() == 'true' || $this->getFilterAttributes()->count()) { ?>
                <div class="bh-sl-filters-container">
                    <?php if($this->canMaxDistance() == 'true'){ ?>
                        <ul class="bh-sl-filters">
                            <li><h4><?php echo $helper->__('Max Distance'); ?></h4></li>
                            <select class="filssterselect" id="bh-sl-maxdistance" name="bh-sl-maxdistance" onchange="submitFinder();">
                                <?php
                                $radiusOptions = explode(',',Mage::getStoreConfig('plugincompany_storelocator/storefinder/radius_options'));
                                $selectedRadius = Mage::getStoreConfig('plugincompany_storelocator/storefinder/radius_default');
                                ?>
                                <option value="100000" <?php if(!$selectedRadius){?>selected="selected"<?php } ?>><?php echo $helper->__('Any Distance'); ?></option>
                                <?php foreach($radiusOptions as $value){ ?>
                                    <option value="<?php echo $value;?>" <?php if($selectedRadius == $value){?> selected="selected"<?php } ?>><?php echo $value; ?> <?php echo $this->getLengthUnitText();?></option>
                                <?php } ?>
                            </select>
                        </ul>
                    <?php } ?>
                    <?php if($this->canNameFilter() == 'true'){ ?>
                        <ul class="bh-sl-filters">
                            <li><h4><?php echo $helper->__('Store Name'); ?></h4></li>
                            <li>
                                <input type="text" id="bh-sl-search" name="bh-sl-search" />
                            </li>
                        </ul>
                    <?php } ?>
    <!--                <div style="float:left;width:100%;text-align:right;">-->
    <!--                    Filter options-->
    <!--                </div>-->
                    <?php foreach($this->getFilterAttributes() as $attr){
                            if(stristr($attr->getFrontendInput(),'select') || stristr($attr->getFrontendInput(),'boolean')){ ?>
                                    <ul id="<?php echo $attr->getAttributeCode();?>-filters-container" class="bh-sl-filters">
                                        <li><h4><?php echo $attr->getStoreLabel(); ?></h4></li>
                                        <li>
                                            <select class="filterselect" data-placeholder="<?php echo $attr->getStoreLabel(); ?>" name="<?php echo $attr->getAttributeCode(); ?>" id="<?php echo $attr->getAttributeCode(); ?>" multiple>
                                                <?php
                                                foreach($attr->getSource()->getAllOptions(false) as $option){ ?>
                                                    <option value="<?php echo $option['value']; ?>"><?php echo $option['label'];?></option>
                                                <?php } ?>
                                            </select>
                                        </li>
                                    </ul>
                            <?php } ?>
                    <?php } ?>
                </div>
            <?php } ?>
        </form>
    </div>

    <div id="map-container" class="bh-sl-map-container">
        <div id="bh-sl-map" class="bh-sl-map"></div>
        <div class="bh-sl-loc-list">
            <ul class="list"></ul>
        </div>
    </div>
</div>

<?php
$isSecure = $this->isSecureUrl();
$jsUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, $isSecure) . 'plugincompany/storelocator/front/';
$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, $isSecure);
?>

<?php $includeLibs = $this->_includeAllLibs(); //all libs for iframe embed ?>

<?php if(Mage::getStoreConfig('plugincompany_storelocator/libraries/jquery') || $includeLibs){?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js',$isSecure); ?>plugincompany/jquerynoconflict.js"></script>
<?php } ?>
<script type="text/javascript" src="<?php echo $jsUrl; ?>js/handlebars.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places<?php echo Mage::helper('plugincompany_storelocator')->getApiKeyQueryString(); ?>"></script>
<script type="text/javascript" src="<?php echo $jsUrl; ?>js/jquery.storelocator.js"></script>
<?php if(Mage::getStoreConfig('plugincompany_storelocator/libraries/fawesome') || $includeLibs){?>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<?php } ?>
<link href="<?php echo Mage::getBaseUrl('js',$isSecure); ?>plugincompany/storelocator/selectivity/selectivity-full.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js',$isSecure); ?>plugincompany/storelocator/selectivity/selectivity-full.js"></script>

<script type="text/javascript">
    alert = function(a) {
        console.log(a);
    };
    jQuery(function() {
        jQuery('.bh-sl-filters-container select').each(function(){
            var id = jQuery(this).attr('id');
            jQuery(this).selectivity();
            jQuery('#' + id).find('select').each(function(){
                jQuery(this).attr('id', id + '-hidden');
            });
            jQuery('#' + id).on('change',function(){
                jQuery(this).find('select').each(function(){
                    if(typeof jQuery(this).attr('oldval') == 'undefined'){

                        //multiple select
                        if(typeof jQuery(this).attr('multiple') != "undefined"){
                            jQuery(this).attr('oldval', jQuery(this).val().sort().join());

                        //normal select
                        }else{
                            jQuery(this).attr('oldval', jQuery(this).val());
                        }
                        jQuery(this).trigger('change');
                        if(jQuery(this).attr('id') == 'bh-sl-maxdistance-hidden'){
                            submitFinder();
                        }
                    }else{
                        var oldVal = jQuery(this).attr('oldval');

                        //no value
                        if(jQuery(this).val() === null){
                            var newVal = "";
                        //multiple select
                        }else if(typeof jQuery(this).attr('multiple') != "undefined"){
                            var newVal = jQuery(this).val().sort().join();
                        ///normal select
                        }else{
                            var newVal = jQuery(this).val();
                        }

                        if(oldVal != newVal){
                            jQuery(this).attr('oldval', newVal);
                            jQuery(this).trigger('change');
                            if(jQuery(this).attr('id') == 'bh-sl-maxdistance-hidden'){
                                submitFinder();
                            }
                        }
                    }
                })
            })
        });
        jQuery('#map-container').storeLocator({
            'dataType': 'json',
            'lengthUnit': '<?php echo Mage::getStoreConfig("plugincompany_storelocator/storefinder/lengthunit");?>',
            'dataLocation': '<?php echo $this->getDataLocation(); ?>',
            'slideMap' : false,
            'fullMapStart': true,
            'distanceAlert': -1,
            'originMarker': true,
            'inlineDirections': true,
            'infowindowTemplatePath': '<?php echo $url; ?>plugincompany_storelocator/js_template/loadInfowindow',
            'listTemplatePath': '<?php echo $url; ?>plugincompany_storelocator/js_template/loadLocationList',
            'KMLinfowindowTemplatePath': '<?php echo $url; ?>plugincompany_storelocator/js_template/loadKmlInfowindow',
            'KMLlistTemplatePath': '<?php echo $url; ?>plugincompany_storelocator/js_template/loadKmlLocationList',
            'taxonomyFilters' : <?php echo $this->getFilterJSON(); ?>,
            'nameSearch': <?php echo $this->canNameFilter(); ?>,
            'nameAttribute' : 'locname',
            'pagination': false,
            'autoGeocode': <?php echo $this->canGeoCode(); ?>,
            'maxDistance': <?php echo $this->canMaxDistance(); ?>,
            'maxDistanceID'            : 'bh-sl-maxdistance-hidden',
            'mapSettings'              : {
                zoom     : <?php echo Mage::getStoreConfig('plugincompany_storelocator/storefinder/zoom'); ?>,
                mapTypeId: google.maps.MapTypeId.ROADMAP
                <?php
                $theme = Mage::getStoreConfig('plugincompany_storelocator/storefinder/theme');
                if(!ctype_space($theme) && $theme){
                    echo ',styles: ' . $theme;
                }
                ?>
            },
            <?php if(Mage::getStoreConfig('plugincompany_storelocator/storefinder/location_marker_img')){?>
                markerImg: '<?php echo Mage::getBaseUrl('media') . 'plugincompany/storefinder/' . Mage::getStoreConfig('plugincompany_storelocator/storefinder/location_marker_img'); ?>',
            <?php } ?>
            <?php if(Mage::getStoreConfig('plugincompany_storelocator/storefinder/origin_marker_img')){?>
                originMarkerImg: '<?php echo Mage::getBaseUrl('media') . 'plugincompany/storefinder/' . Mage::getStoreConfig('plugincompany_storelocator/storefinder/origin_marker_img'); ?>',
            <?php } ?>
            originMarker: <?php echo (Mage::getStoreConfigFlag('plugincompany_storelocator/storefinder/originmarker') ? 'true' : 'false'); ?>,
            storeLimit : <?php $var = Mage::getStoreConfig('plugincompany_storelocator/storefinder/storelimit'); echo ($var ? $var : '-1'); ?>,
            defaultLoc: <?php echo (Mage::getStoreConfigFlag('plugincompany_storelocator/storefinder/defaultloc') ? 'true' : 'false'); ?>,
            defaultLat: <?php $var = Mage::getStoreConfig('plugincompany_storelocator/storefinder/defaultloclat'); echo ($var ? $var : '0'); ?>,
            defaultLng: <?php $var = Mage::getStoreConfig('plugincompany_storelocator/storefinder/defaultloclng'); echo ($var ? $var : '0'); ?>,
            markerDim: { height: 38, width: 38 },
            originMarkerDim: { height: 38, width: 38 }
        }, function(){

        });
        var autocomplete = new google.maps.places.Autocomplete(
            /** @type {HTMLInputElement} */(document.getElementById('bh-sl-address')),
            { types: ['geocode'], componentRestrictions: {country: '<?php echo Mage::getStoreConfig('general/country/default'); ?>'} });
        // When the user selects an address from the dropdown,
        // populate the address fields in the form.
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            jQuery('#bh-sl-user-location').submit();
        });
    });
    function submitFinder(){
        jQuery('#bh-sl-user-location').submit();
    }

    Handlebars.registerHelper('displaystars', function(options) {

        numOfStars = this.rating > 0 ? this.rating : 0;

        string = '';
        for(x=1; x <= 5; x++){
            className = (x <= numOfStars) ? 'fa-star' : 'fa-star-o';

            string += '<i class="fa ' + className + '"></i>'
        }

       return string;
    });
</script>

<?php if($includeLibs){ ?>

    <style>
        .selectivity-multiple-input-container{
            max-height: 200px;
        }
        .selectivity-multiple-input-container input {
            width:100%!important;
        }
    </style>
<?php } ?>

    <?php
        ;
    ?>
</div>

<?php if($getAddr = $this->getRequest()->getParam('address')){ ?>
    <script>
        jQuery(document).ready(function(){
            setTimeout(function(){
                jQuery('#bh-sl-address').val('<?php echo $getAddr; ?>');jQuery('#bh-sl-submit').trigger('click');
            },2000);
        })
    </script>
<?php } ?>
