<?php

	//Give Add new page url with your key
	$addNewPageUrl = Mage::helper('popupbuilder/GetData')->getPageUrl('edit');
?>
<h2>Add New Popup</h2>
<div class="popups-wrapper">
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/image';?>">
		<div class="popups-div image-popup">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/html';?>">
		<div class="popups-div html-popup">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/fblike';?>">
		<div class="popups-div fblike-popup">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/iframe';?>">
		<div class="popups-div iframe-popup">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/video';?>">
		<div class="popups-div video-popup">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/agerestriction';?>">
		<div class="popups-div age-restriction">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/countdown';?>">
		<div class="popups-div countdown">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/social';?>">
		<div class="popups-div sg-social">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/exitintent';?>">
		<div class="popups-div sg-exit-intent">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/subscription';?>">
		<div class="popups-div sg-subscription">
		</div>
	</a>
	<a class="create-popup-link" href="<?php echo $addNewPageUrl.'type/contactform';?>">
		<div class="popups-div sg-contact-form">
		</div>
	</a>
</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/PopupBuilder/sg_popup_backend.js') ?>"></script>