<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/PopupBuilder/sg_popup_rangeslider.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/PopupBuilder/sg_popup_backend.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/PopupBuilder/bootstrap-tagsinput.js') ?>"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/bootstrap-tagsinput.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/sg_popup_rangeslider.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/jquery-ui.min.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/animate.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/sg_flipclock.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/colorpicker.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/PopupBuilder/jquery.datetimepicker.min.css') ?>">

