<?php echo $this->getChildHtml('checkout.onepage.login.extra')?>
<?php echo $this->getChildHtml('login_before')?>

<div class="well well--block block block-checkout-register">
    <div class="well__header">
        <strong class="well__header__title"><span><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></span></strong>
    </div>
    <div class="block-content">
        <h3><strong><?php echo $this->__('Register and save time!') ?></strong></h3>
        <p><?php echo $this->__('Register with us for future convenience:') ?></p>
        <ul class="ul">
            <li><?php echo $this->__('Fast and easy check out') ?></li>
            <li><?php echo $this->__('Easy access to your order history and status') ?></li>
        </ul>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
        <ul class="form-list">
          <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
            <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <li class="control">
                <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
            </li>
            <?php endif; ?>
            <li class="control">
                <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
            </li>
        </ul>
        <?php else: ?>
        <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>

        <div class="buttons-set a-center">
            <p class="required">&nbsp;</p>
            <button type="button" class="btn" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
        </div>

    </div>
</div>

<div class="well well--block block block-checkout-login">
    <div class="well__header">
        <strong class="well__header__title"><span><?php echo $this->__('Login') ?></span></strong>
    </div>
    <div class="block-content">

        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <fieldset>
                <p class="a-center"><?php echo $this->__('Please log in below:') ?></p>
                <ul class="form-list">
                    <li class="form__group">
                        <label for="login-email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                        </div>
                    </li>
                    <li class="form__group">
                        <label for="login-password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <p class="a-center"><?php echo $this->__('* Required Fields') ?></p>
            </fieldset>
        </form>

        <div class="buttons-set a-center">
            <button type="submit" class="btn" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="checkout-forgot-password"><?php echo $this->__('Forgot your password?') ?></a>
        </div>

    </div>
</div>

<div class="clear"></div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
