<?php $posts = $this->getPosts(); ?>
<!--<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php // echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            
        </div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>

        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
        <div class="postDetails">
            <?php if ($this->getCommentsEnabled()): ?>
                <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
            <?php endif; ?>
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <?php echo Mage::helper('blog')->__('Posted in'); ?>
                <?php foreach ($postCats as $data): ?>
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo Mage::helper('blog')->__('Posted'); ?>
            <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
    </div>
<?php endforeach; ?>
<?php // echo $this->getChildHtml('aw_blog_comments_toolbar'); ?> -->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bloc_on_parle_de_nous')->toHtml(); ?>
<br>

  <div class="posts">
    <?php foreach ($posts as $post): ?>
          <div class="actuWrapper">
            <div class="image">
                 <span class="helper"></span><img data-href="<?php echo $post['address'] ?>" src="/media/wysiwyg/images/<?php echo $post['filename'] ?>" alt="image news" />
            </div>
            <div class="text_news">
                <div class="title">
                  <h2><a href="<?php echo $post['address'] ?>"><?php echo $post->getTitle() ?></a></h2>
                </div>
                <div class="date">
                    <?php $_ct= new Zend_Date($post->getCreatedTime());
      echo $_ct->toString('dd MMM yyyy'); ?>
                </div>
                <div class="contenu">
                  <?php echo $post['post_content']; ?>
                </div>

                <div class="lien-article">
                  <img src="/media/wysiwyg/images/fleche.png" alt="fleche lire la suite de la news" class="fleche_news"><a href="<?php echo $post['address']; ?>">Lire plus</a>
                </div>                    
            </div>

          </div>
    <?php endforeach; ?>
  </div>
