<?php
/*
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
/**
 * Store location comments form template
 *
 * @category    Plugincompany
 * @package     Plugincompany_Storelocator
 * @author      Milan Simek
 */
?>
<?php
    $helper = Mage::helper('plugincompany_storelocator');
?>

<?php $data = $this->getCommentData();?>
<div class="form-add">
    <h2><?php echo $helper->__('Write Your Comment') ?></h2>
    <?php if ($this->getAllowWriteCommentFlag()): ?>
        <form action="<?php echo $this->getAction() ?>" method="post" id="comment-form">
            <fieldset>
                <ul class="form-list">
                    <li>
                        <label for="nickname_field" class="required"><em>*</em><?php echo $helper->__('Nickname') ?></label>
                        <div class="input-box">
                            <input type="text" name="name" id="name_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getName()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="nickname_field" class="required"><em>*</em><?php echo $helper->__('E-mail') ?></label>
                        <div class="input-box">
                            <input type="text" name="email" id="email_field" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($data->getEmail()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="title_field" class="required"><em>*</em><?php echo $helper->__('Comment title') ?></label>
                        <div class="input-box">
                            <input type="text" name="title" id="title_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="review_field" class="required"><em>*</em><?php echo $helper->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment_field" cols="5" rows="3" class="required-entry"><?php echo $this->htmlEscape($data->getComment()) ?></textarea>
                        </div>
                    </li>
                    <?php if($this->isRatingEnable()): ?>
                    <li>
                        <label for="review_field" class="required"><em>*</em><?php echo $helper->__('Rating') ?></label>
                        <div class="input-box">
                           <div class="starrr"  data-input-id="#rating"></div>
                           <input type="text" name="rating" id="rating" class="form-control-rating required-entry validate-digits-range-1-5" />
                        </div>
                    </li>
                    <?php else: ?>
                        <input type="text" name="rating" value="0"  class="form-control-rating" />
                    <?php endif; ?>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $helper->__('Submit Comment') ?>" class="button"><span><span><?php echo $helper->__('Submit Comment') ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">var commentForm = new VarienForm('comment-form');</script>
    <?php else: ?>
    <p class="review-nologged" id="comment-form">
        <?php echo $helper->__('Only registered users can write comments. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
