<?php
/*
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
/**
 * Store location comments list template
 *
 * @category    Plugincompany
 * @package     Plugincompany_Storelocator
 * @author      Milan Simek
 */
?>
<?php
    $helper = Mage::helper('plugincompany_storelocator');
?>

<?php $_storelocation = $this->getStorelocation()?>
<?php if ($_storelocation->getAllowComments()) : ?>
    <?php $_comments = $this->getComments(); ?>
    <?php if (count($_comments)) : ?>
        <div class="box-collateral box-reviews" id="storelocation-reviews">
            <h2><?php echo $helper->__('Comments for: %s', $_storelocation->getLocname()) ?></h2>
            <?php echo $this->getPagerHtml() ?>
            <div class="commentlist">
                <?php foreach ($_comments as $_comment):?>
                    <div class="storecomment">
                        <p class="commenttitle"><?php echo $this->htmlEscape($_comment->getTitle()) ?></p>
                        <?php if($this->isRatingEnable()): ?>
                        <div class="starrr" data-rating='<?php echo $_comment->getRating(); ?>' data-disabled='true'></div>
                         <?php endif; ?>
                        <div class="commentcontent">
                            <?php echo nl2br($this->htmlEscape($_comment->getComment())) ?>
                        </div>
                        <div class="author"><?php echo $helper->__('On %s by %s', $this->formatDate($_comment->getCreatedAt(), 'long'), $this->htmlEscape($_comment->getName()))?></div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('comment_form') ?>
<?php endif;?>
<style type="text/css">
    .storelocator-view #storelocation-reviews > h2 {
        display: none;
    }
</style>

<script type="text/javascript">
jQuery(function(){
    jQuery('.starrr').each(function(){
      jQuery(this).starrr({
        rating: parseInt(jQuery(this).data('rating'), 10),
        readOnly: jQuery(this).data('disabled')
      });
    })

    jQuery('.starrr').on('starrr:change', function(e, value){
      id = jQuery(e.delegateTarget).data('input-id')
      jQuery(id).val(value);
    });
});
</script>