<?php
/**
 * Top menu for store
 *
 * @see Queldorei_Navigation_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<!-- navigation BOF -->
<?php $_menu = $this->renderCategoriesMenuHtml(0, 'level-top', 'sub-wrapper' ) ?>
<?php if($_menu): ?>
<div class="nav-container">
    <div class="nav-top-title"><div class="icon"><span></span><span></span><span></span></div><a href="#"><?php echo $this->__('Navigation'); ?></a></div>
    <ul id="queldoreiNav">
	    <?php if (Mage::getStoreConfig('shoppersettings/navigation/home')): ?>
         <li class="level0 level-top">
         	<a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home'); ?></span></a>
         </li>
     <?php endif; ?>
        <?php
        echo $_menu;
        $custom_tab = Mage::getModel('cms/block')
	        ->setStoreId( Mage::app()->getStore()->getId() )
	        ->load('shopper_navigation_block');
        if($custom_tab->getIsActive()) {
            echo '
            <li class="level0 level-top parent custom-block">
                <a href="#" class="level-top">
                    <span>'.$custom_tab->getTitle().'</span>
                </a>
                <div class="sub-wrapper" style="width:'.Mage::getStoreConfig('shoppersettings/navigation/custom_block_width').'px">'.$this->getLayout()->createBlock('cms/block')->setBlockId('shopper_navigation_block')->toHtml().'</div>
            </li>';
        }
        ?>
        <li class="level0 level-top">
            <a href="/faq"><span><?php echo $this->__('INFORMATIONS'); ?></span></a>
            <div class="sub-wrapper" style="width:485px">
                <ul class="level0">
                    <li class="">
                        <ol>
                            <li class="level1 nav-1-1 first">
                                <a href="/manufacturing">
                                    <span>Fabrication <img class="category_image" width="150" src="/media/wysiwyg/fabrication-1.png" alt="Fabrication"></span>
                                </a>
                            </li>
                        </ol>
                    </li>
                    <li class="">
                        <ol>
                            <li class="level1 nav-1-1 first">
                                <a href="/faq">
                                    <span>FAQ <img class="category_image" width="150" src="/media/wysiwyg/faq.jpg" alt="FAQ"></span>
                                </a>
                            </li>
                        </ol>
                    </li>
                </ul>
            </div>
        </li>
        <!--<li class="level0 level-top">
            <a href="/social"><span><?php echo $this->__('News'); ?></span></a>
            <div class="sub-wrapper" style="width:485px">
                <ul class="level0">
                    <li class="">
                        <ol>
                            <li class="level1 nav-1-1 first">
                                <a href="/social">
                                    <span>Social <img class="category_image" width="150" src="/media/wysiwyg/jumbo-social.jpg" alt="Social"></span>
                                </a>
                            </li>
                        </ol>
                    </li>
                    <li class="">
                        <ol>
                            <li class="level1 nav-1-1 first">
                                <a href="/summer-project">
                                    <span>Summer Project <img class="category_image" width="150" src="/media/wysiwyg/jbsp-1.jpg" alt="Summer Project"></span>
                                </a>
                            </li>
                        </ol>
                    </li>
                </ul>
            </div>
        </li>
        <li class="level0 level-top">
            <a href="http://blog.jumbobag.fr/" target="_blank"><span><?php echo $this->__('Blog'); ?></span></a>
        </li>-->
    </ul>
</div>
<?php endif ?>
<!-- navigation EOF -->
