<footer>
  <div class="arguments-footer row-boostrap">
    <div class="arguments-footer-inner row">
      <div class="argument-footer col-sm-3 col-xs-6">
        <div class="image-wrapper wow fadeIn">
          <img src="/skin/frontend/jumbobag/default/images/box.svg" alt="Livraison gratuite à partir de 100€" />
        </div>
        <h3>Livraison gratuite</h3>
        <p>à partir de 100€ d'achats</p>
      </div>
      <div class="argument-footer col-sm-3 col-xs-6">
        <div class="image-wrapper wow fadeIn" data-wow-delay="0.1s">
          <img src="/skin/frontend/jumbobag/default/images/location.svg" alt="Venez en magasin" />
        </div>
        <h3>Venez en magasin</h3>
        <p>Trouvez un revendeur près de chez vous</p>
        <a href="/stores/store-finder.html"><span>revendeurs</span></a>
      </div>
      <div class="argument-footer col-sm-3 col-xs-6">
        <div class="image-wrapper wow fadeIn" data-wow-delay="0.2s">
          <img src="/skin/frontend/jumbobag/default/images/euro.svg" alt="Financement" />
        </div>
        <h3>Financement</h3>
        <p>Options de paiement disponibles</p>
        <a href="/payment-mode"><span>en savoir plus</span></a>
      </div>
      <div class="argument-footer col-sm-3 col-xs-6">
        <div class="image-wrapper wow fadeIn" data-wow-delay="0.3s">
          <img src="/skin/frontend/jumbobag/default/images/bulles.svg" alt="Se faire aider pour un achat" />
        </div>
        <h3>Besoin d'aide ?</h3>
        <p>
            Une question avant d'acheter&nbsp;?<br>
            Appelez-nous : 09 72 60 09 18<br>
            <small>(appel non surtaxé)</small>
        </p>
      </div>
    </div>
  </div>

  <div class="footer-newsletter">
  <?php
    echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_home.phtml')->toHtml();
    ?>
  </div>
  
  <div class="liens-footer row-bootstrap">
    <div class="liens-footer-inner row">
      <div class="social-links col-sm-3">
        <div class="responsive-footer">
          <ul class="social">
            <li><a class="facebook" href="http://facebook.com/jumbobag" target="_blank"><img src="/skin/frontend/jumbobag/default/images/facebook-footer.png" alt="rejoignez nous sur facebook" /></a></li>
            <li><a class="twitter" href="http://twitter.com/jumbo_bag" target="_blank"><img src="/skin/frontend/jumbobag/default/images/twitter-footer.png" alt="rejoignez nous sur twitter" /></a></li>
            <li><a class="email" href="mailto:contact@jumbobag.fr"><img src="/skin/frontend/jumbobag/default/images/mail-footer.png" alt="contactez nous par mail" /></a></li>
            <li><a class="google" href="https://plus.google.com/+JumbobagFr1" rel="publisher" target="_blank"><img src="/skin/frontend/jumbobag/default/images/google-footer.png" alt="rejoignez nous sur google plus" /></a></li>
            <li><a class="youtube" href="https://www.youtube.com/channel/UCaKoRsdihPQdTs8Gv9q6iuQ" rel="publisher" target="_blank"><img src="/skin/frontend/jumbobag/default/images/youtube-footer.png" alt="rejoignez nous sur youtube" /></a></li>
          </ul>
          <div class="bank">
            <ul>
              <li class="payments">
              <img src="/media/wysiwyg/1416523843_payment_method_paypal-128.png" alt="regler vos achats via paypal">
              <img src="/media/wysiwyg/1416523842_payment_method_master_card-128.png" alt="regler vos achats via master card">
              <img src="/media/wysiwyg/1416523839_payment_method_card_visa-128.png" alt="regler vos achats via visa">
              </li>
            </ul>
          </div>
        </div>
      </div>

      <?php echo $this->getChildHtml('shopper_footer_press') ?>

      <?php echo $this->getChildHtml('shopper_footer_information') ?>

      <?php echo $this->getChildHtml('shopper_footer_contact') ?>
    </div>
    <div class="footer-bank-mobile col-sm-4" style="display: none;">
            <ul>
              <li class="payments">
              <img src="/media/wysiwyg/1416523843_payment_method_paypal-128.png" alt="regler vos achats via paypal">
              <img src="/media/wysiwyg/1416523842_payment_method_master_card-128.png" alt="regler vos achats via master card">
              <img src="/media/wysiwyg/1416523839_payment_method_card_visa-128.png" alt="regler vos achats via visa">
              </li>
            </ul>
    </div>
    <div class="copyright-wrapper">
      <p>© COPYRIGHT 2017, JumboBag</p>
    </div>
  </div>
</footer>
