<?php
$config = Mage::getStoreConfig('shoppersettings', Mage::app()->getStore()->getId());
if (isset($config['design']['search_field']) && $config['design']['search_field'] == 0) :
	?>
<div class="search-top-container">
    <div class="search-top"></div>
    <div class="search-form">
        <div class="search-form-border"></div>
        <div class="search-top-title"><span class="icon"></span><?php echo $this->__('Search'); ?></div>
        <form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
            <div class="form-search">
                <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>"
                       value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text"/>
                <button type="submit" title="<?php echo $this->__('Search') ?>"></button>
            </div>
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <script type="text/javascript">
                //<![CDATA[
                var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
                searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
                //]]>
            </script>
        </form>
    </div>
</div>
<?php else : ?>
<div class="search-top-container">
    <form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
        <div class="form-search">
            <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>"
                   value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text"/>
            <button type="submit" title="<?php echo $this->__('Search') ?>"></button>
        </div>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
            //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
            //]]>
        </script>
    </form>
</div>
<?php endif; ?>