<?php
/**
 * @var $this		Mage_Catalog_Block_Product_View_Media
 * @var $product	Mage_Catalog_Model_Product
 */
?>
<?php
	$product = $this->getProduct();
	$outputHelper = $this->helper('catalog/output');
	$helper = $this->helper('shoppersettings/image');
    $config = Mage::getStoreConfig('shoppersettings');

    list($defaultImgX, $defaultImgY) = $helper->getDefaultSize();
    list($imgX, $imgY) = $helper->getMainSize();
    if ( $imgX > 800 ) {
        $imgX = 800;
        $imgY = $helper->calculateHeight($imgX);
    }
    list($thumbX, $thumbY) = $helper->getThumbSize();
	list($real_thumbX, $real_thumbY) = $helper->getThumbSize();
	if ( $real_thumbX < 140 ) {
		$real_thumbX = 140;
		$real_thumbY = $helper->calculateHeight($real_thumbX);
	}
?>

<?php if ($product->getImage() != 'no_selection' && $product->getImage()): ?>

	<p class="product-image">
        <a class="product-image-link" href="<?php echo $this->helper('catalog/image')->init($product, 'image'); ?>" rel="lighbox-zoom-gallery" >
            <img class="product-image-img" src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(500, 500); ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(1000, 1000); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
        </a>
    </p>

<?php else: ?>

    <p class="product-image">
        <?php
            $_img = '<img class="product-image-img" src="'.$this->helper('catalog/image')->init($product, 'image')->resize($imgX, $imgY).'" data-srcX2="'.$this->helper('catalog/image')->init($product, 'image')->resize(500, 500).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
            echo $outputHelper->productAttribute($product, $_img, 'image');
        ?>
    </p>

<?php endif; ?>

<ul id="product-gallery" class="product-gallery clearfix"></ul>


<?php
if ($product->getData('innersense_id')) {
    echo $this->getChildHtml('innersense_3dviewer');
    ?>
    <script type="text/javascript">
        if (!window.viewer3DOptions) {
            window.viewer3DOptions = {}
        }

        window.viewer3DOptions.getEntryFromElement = function (element) {
            var match = element.name.match(/super_attribute\[(\d+)\]/)
            var name = match ? match[1] : null
            var value = element.value;

            if (['radio', 'checkbox'].indexOf(element.type) > -1 && !element.checked) {
                value = null
            }

            return {
                name: name,
                value: value
            }
        }

        window.viewer3DOptions.getPrice = function () {
            var priceBoxSelector = '.special-price > .price, .regular-price > .price'
            var price = document.querySelector(priceBoxSelector).innerHTML
            // Only keep numbers and commas
            return price.replace(/[^0-9$.,]/g, '');
        }

        window.viewer3DOptions.bypassListeners = true;

        window.viewer3DOptions.ready = function () {
            window.viewer3DOptions.init();
            if (Innersense.isSupported && window.viewer3D) {
                var swatches = document.querySelectorAll('.swatch-link')
                for (var i = 0; i < swatches.length; i++) {
                    swatches[i].addEventListener('click', window.viewer3DOptions.handleOptionsUpdated)
                }
                window.viewer3DOptions.handleOptionsUpdated()
            }
        }
    </script>
<?php } ?>
