<?php
/**
 * @var $this		Mage_Catalog_Block_Product_View_Media
 * @var $product	Mage_Catalog_Model_Product
 */
?>
<?php
	$product = $this->getProduct();
	$outputHelper = $this->helper('catalog/output');
	$helper = $this->helper('shoppersettings/image');
    $config = Mage::getStoreConfig('shoppersettings');

    list($defaultImgX, $defaultImgY) = $helper->getDefaultSize();
    list($imgX, $imgY) = $helper->getMainSize();
    if ( $imgX > 800 ) {
        $imgX = 800;
        $imgY = $helper->calculateHeight($imgX);
    }
    list($thumbX, $thumbY) = $helper->getThumbSize();
	list($real_thumbX, $real_thumbY) = $helper->getThumbSize();
	if ( $real_thumbX < 140 ) {
		$real_thumbX = 140;
		$real_thumbY = $helper->calculateHeight($real_thumbX);
	}
?>

<?php if ($product->getImage() != 'no_selection' && $product->getImage()): ?>

	<p class="product-image">
        <a class="product-image-link" href="<?php echo $this->helper('catalog/image')->init($product, 'image'); ?>" rel="lighbox-zoom-gallery" >
            <img class="product-image-img" src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(500, 500); ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(1000, 1000); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
        </a>
    </p>

<?php else: ?>

    <p class="product-image">
        <?php
            $_img = '<img class="product-image-img" src="'.$this->helper('catalog/image')->init($product, 'image')->resize($imgX, $imgY).'" data-srcX2="'.$this->helper('catalog/image')->init($product, 'image')->resize(500, 500).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
            echo $outputHelper->productAttribute($product, $_img, 'image');
        ?>
    </p>

<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <ul id="shopper_gallery_carousel" class="jcarousel-skin-tango clearfix">
    <?php foreach ($this->getGalleryImages() as $_image): ?>
    	<?php //Skip, if no image
        	if ($_image->getFile() == NULL)
			continue; ?>
        <li data-label="<?php echo $this->escapeHtml($_image->getLabel()) ?>" >
            <a href='<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile()); ?>' class='lighbox-zoom-gallery' rel='lighbox-zoom-gallery' title='<?php echo $this->escapeHtml($_image->getLabel()) ?>' >
            <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize(500, 500); ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize(1000, 1000); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"/>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
    <div class="jcarousel-controls">
        <a href="#" class="jcarousel-prev-horizontal" id="shopper_gallery_prev"></a>
        <a href="#" class="jcarousel-next-horizontal" id="shopper_gallery_next"></a>
    </div>
</div>
<?php endif; ?>
