<?php
/*
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
/**
 * customer Store locations comments view
 * @category    Plugincompany
 * @package     Plugincompany_Storelocator
 * @author      Milan Simek
 */
?>
<?php
    $helper = Mage::helper('plugincompany_storelocator');
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->getComment()->getTitle() ?></h1>
</div>
<div class="comment-view">
    <h2>
        <a class="product-name" href="<?php echo $this->getStorelocation()->getStorelocationUrl()?>">
            <?php echo $this->getStorelocation()->getLocname()?>
        </a>
    </h2>
    <div class="comment-date">
        <?php echo $helper->__('On %s you wrote:', $this->formatDate($this->getComment()->getCreatedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_FULL))?>
    </div>
    <div>
        <?php echo Mage::helper('core')->escapeHtml($this->getComment()->getComment());?>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $helper->__('Back') ?></a></p>
    </div>
</div>