<?php
/**
* Ultimate_Slider extension
*
* NOTICE OF LICENSE
*
* This source file is subject to the MIT License
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/mit-license.php
*/
/**
*
* @category       Images & Media
* @package        Ultimate_Slider
* @copyright      Copyright (c) 2015
* @license        http://opensource.org/licenses/mit-license.php MIT License
*/
/**
* Slider list template
*
* @category    Images & Media
* @package     Ultimate_Slider
* @author      Rajasingh and Manikandan D
* @modified    2015-11-21 04:54:53 PM IST
*/
?>
<div class="slideshow-container">
    <ul class="slideshow">
        <?php foreach($this->retrieveData() as $slider){ ?>
        <?php if((!empty($slider['video_url']!='')) || (!empty($slider['image']))) { ?>        
        <li>
        <?php if(($slider['video_url']!='') && (!empty($slider['video_url']))){ ?>
            
                <iframe frameborder="0" 
                        width="100%" 
                        height="720"
                        src="<?php echo $slider['video_url'];?>" 
                        allowfullscreen>
                </iframe>            

        <?php } else { ?>

        <?php if (substr($slider['image'], -4) == '.jpg') { ?>

            <a href="#">
            <img src="<?php echo Mage::getBaseUrl('media');?>wysiwyg/<?php echo $slider['image'];?>"
            alt="<?php echo $slider['alt_text'];?>"
            title="<?php echo $slider['title'];?>"
            height="720"
            />
            </a>
        <?php } else { ?>
            <video width="100%" height="700" controls="controls">
                <source src="<?php echo Mage::getBaseUrl('media');?>wysiwyg/<?php echo $slider['image'];?>"
                        alt="<?php echo $slider['alt_text'];?>"
                        title="<?php echo $slider['title'];?>"
                >
                Your browser does not support the video tag. But you could include an iframe/embeded video here.
            </video> 
        <?php } }?>
        </li>
        <?php } ?>
    <?php } ?>
    </ul>
        <div class="slideshow-pager">&nbsp;</div>
        <span class="slideshow-prev">&nbsp;</span> 
        <span class="slideshow-next">&nbsp;</span>
</div>
<?php if(Mage::getStoreConfig('ultimate_slider/slider/roll_slides_active')==0) { ?>
<script type="text/javascript">
    $j(document).ready(function () {
    // ==============================================
    // UI Pattern - Slideshow
    // ==============================================
    $j('.slideshow-container .slideshow')
        .cycle({
            slides: '> li',
            pager: '.slideshow-pager',
            pagerTemplate: '<span class="pager-box"></span>',
            speed: 6000,
            pauseOnHover: true,
            swipe: true,
            prev: '.slideshow-prev',
            next: '.slideshow-next',
            fx: 'scrollHorz'
        }).cycle('pause');
});
</script>
<?php } ?>