<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery-2.0.2.min.js"></script>
<script type="text/javascript">
    jQuery.noConflict();
</script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.isotope.min.js"></script>
<script type="text/javascript">
    jQuery(window).load(function () {
        var $ = jQuery;
        var $container = $('#gallery-content-center');
        var $filters = $('[data-categoryid]');

        $filters.on('click', function () {
            var $filter = $(this);
            var categoryId = $filter.data('categoryid');
            categoryId = parseInt(categoryId, 10);
            selectFilter($filter);
            filterProducts(categoryId);
        });

        var filterProducts = function (categoryId) {
            $container.isotope({
                itemSelector: 'li',
                filter: function (index, product) {
                    return isInCategory(product, categoryId);
                }
            });
        };

        var isInCategory = function (product, categoryId) {
            var categoryIds = product.dataset.categoryids
                .split(',')
                .map(function (catId) {
                    return parseInt(catId, 10);
                })
            ;
            return categoryIds.indexOf(categoryId) !== -1;
        };

        var selectFilter = function ($filter) {
            $filters.closest('.gallery-header-center-right-links').removeClass('gallery-header-center-right-links-current');
            $filter.addClass('gallery-header-center-right-links-current');
        };
    });


</script>

<style type="text/css">
    .showDiv {
        display: block;
    }

    .hideDiv {
        display: none;
    }
</style>

<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$helper = $this->helper('shoppersettings/image');

$listX = 230;
$listY = 230;
?>
<?php if (!$_productCollection->count()): ?>
    <?php
    $empty_category_block = Mage::getModel('cms/block')
        ->setStoreId(Mage::app()->getStore()->getId())
        ->load('shopper_empty_category');
    if ($empty_category_block->getIsActive()) {
        echo $this->getLayout()->createBlock('cms/block')->setBlockId('shopper_empty_category')->toHtml();
    } else { ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php } ?>
<?php else: ?>

<div id="gallery">
    <div id="gallery-header">
        <div id="gallery-header-center">
            <?php $_helper = Mage::helper('catalog/category') ?>
            <?php $_categories = $_helper->getStoreCategories() ?>
            <?php $currentCategory = Mage::registry('current_category') ?>
            <?php if (count($_categories) > 0): ?>

                <?php foreach ($_categories as $_category): ?>


                    <?php if ($currentCategory && $currentCategory->getId() == $_category->getId()): ?>
                        <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                        <?php $_subcategories = $_category->getChildrenCategories() ?>
                        <?php if (count($_subcategories) > 0): ?>
                            <div id="gallery-header-center-right">
                                <div
                                    class="gallery-header-center-right-links gallery-header-center-right-links-current topsubmenu group-1"
                                    id="filter-all">

                                    <a data-categoryid="<?= $_category->getId() ?>">Tout les produits</a>

                                </div>
                                <?php foreach ($_subcategories as $_subcategory): ?>
                                    <div
                                        class="gallery-header-center-right-links topsubmenu group-<?php echo $_subcategory->getId() ?>"
                                        data-group="<?php echo $_subcategory->getId() ?>"
                                        id="filter-<?php echo $_subcategory->getId() ?>">

                                        <a class="sub_category_url-<?php echo $_subcategory->getId() ?>"
                                           data-categoryid="<?= $_subcategory->getId() ?>">
                                            <?php echo $_subcategory->getName() ?>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                            </div>

                        <?php endif; ?>
                    <?php endif; ?>

                <?php endforeach; ?>

            <?php endif; ?>

        </div>
        <div class="wrapper-en-savoir-plus tissu wrapper-filters-catalog">
            <div class="bouton">
                <p>Filtres<br/><i class="fa fa-plus-circle" aria-hidden="true"></i></p>
            </div>
            <div class="inner-en-savoir-plus">
                <?php if (count($_categories) > 0): ?>

                    <?php foreach ($_categories as $_category): ?>


                        <?php if ($currentCategory && $currentCategory->getId() == $_category->getId()): ?>
                            <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                            <?php $_subcategories = $_category->getChildrenCategories() ?>
                            <?php if (count($_subcategories) > 0): ?>


                                <?php foreach ($_subcategories as $_subcategory): ?>


                                    <?php $_sub_subcategories = $_subcategory->getChildrenCategories() ?>
                                    <?php if (count($_sub_subcategories) > 0): ?>
                                        <div class="submenufilter group-<?php echo $_subcategory->getId() ?>"
                                             data-group="<?php echo $_subcategory->getId() ?>">
                                            <div id="gallery-header-center-right">
                                                <?php /*?><div class="gallery-header-center-right-links gallery-header-center-right-links-current " id="filter-all"><a class="sub_category_url-<?php echo $_subcategory->getId() ?>">Afficher tout</a></div><?php */ ?>
                                                <?php foreach ($_sub_subcategories as $_sub_subcategory): ?>
                                                    <div class="gallery-header-center-right-links "
                                                         id="filter-<?php echo $_sub_subcategory->getId() ?>">

                                                        <a class="sub_category_url-<?php echo $_sub_subcategory->getId() ?>"
                                                           data-categoryid="<?= $_sub_subcategory->getId() ?>">
                                                            <?php echo $_sub_subcategory->getName() ?>
                                                        </a>

                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>

                                <?php endforeach; ?>


                            <?php endif; ?>
                        <?php endif; ?>

                    <?php endforeach; ?>

                <?php endif; ?>
            </div>
            <script type="text/javascript">
                jQuery('.gallery-header-center-right-links.topsubmenu').click(function () {
                    jQuery('.submenufilter.active').removeClass('active');


                    var newDisplay = 'none';
                    jQuery('.submenufilter').css('display', newDisplay);
                    var newDisplayview = 'block';
                    jQuery('.submenufilter.active').css('display', newDisplayview);
                    jQuery('.submenufilter.group-' + jQuery(this).data('group')).addClass('active');
                    jQuery('.fa').removeClass('fa-times-circle isOutin');
                    jQuery('.fa').addClass('fa-plus-circle');
                    jQuery('.inner-en-savoir-plus').load();
                    var h = jQuery('.submenufilter.active').height();


                    if (h != null) {
                        jQuery(".wrapper-en-savoir-plus.tissu").addClass('showDiv');
                        jQuery(".wrapper-en-savoir-plus.tissu").removeClass('hideDiv');
                    } else {
                        jQuery(".wrapper-en-savoir-plus.tissu").addClass('hideDiv');
                        jQuery(".wrapper-en-savoir-plus.tissu").removeClass('showDiv');
                    }

                });

            </script>
            <script type="text/javascript">
                jQuery('.fa-plus-circle').click(function () {
                    var display = jQuery('.submenufilter.active').css('display');
                    var newDisplay = (display == 'block') ? 'none' : 'block';
                    jQuery('.submenufilter.active').css('display', newDisplay);
                });
                jQuery('.fa').click(function () {
                    jQuery(this).toggleClass('fa-plus-circle fa-times-circle');
                    jQuery(this).toggleClass(' isOutin');
                    jQuery(this).parent().toggleClass('close_icon');

                });
            </script>
        </div>
    </div>

    <div id="gallery-content">

        <div id="gallery-content-center">
            <?php
            $_collectionSize = $_productCollection->count();

            $pageLayout = $this->getLayout()->getBlock('root')->getTemplate();
            if (strpos($pageLayout, '2columns')) {
                $grid_class = 'two_columns_' . Mage::getStoreConfig('shoppersettings/catalog/grid_columns_2col');
            } else {
                $grid_class = 'one_column_' . Mage::getStoreConfig('shoppersettings/catalog/grid_columns_1col');
            }
            $imgX = 230;
            $imgY = 230;
            ?>
            <ul class="products-grid <?php echo $grid_class; ?>">
                <?php $i = 0;
                foreach ($_productCollection as $_product): ?>
                    <li class="item all" itemscope itemtype="http://schema.org/Product"
                        data-categoryids="<?= Mage::helper('jumbobag_catalog')->getDataCategotyIds($_product); ?>">
                        <div class="regular abcdef">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"
                               itemprop="url">
                                <?php $stockItem = $_product->getStockItem(); ?>
                                <?php if (!$stockItem->getIsInStock()): ?>
                                    <div class="out-of-stock-label">Épuisé</div>
                                <?php endif; ?>
                                <div
                                    class="featured-product-label"><?php echo $_product->getData('featured_product') ?></div>
                                <?php echo $this->helper('shoppersettings')->getLabel($_product); ?>
                                <?php // Display Discount percents start ?>
                                <?php $_finalPrice = $_product->getPrice();
                                $_price = $_product->getFinalPrice();

                                if ($_price < $_finalPrice): ?>
                                    <?php $_savingPercent = 100 - round(($_price / $_finalPrice) * 100); ?>
                                    <div class="sale-label sale-top-right"><?php echo $_savingPercent; ?>%</div>
                                <?php endif; ?>
                                <?php // Display Discount percent end ?>
                                <img
                                    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>"
                                    data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX * 2, $imgY * 2) ?>"
                                    width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>"
                                    alt="<?php echo $this->htmlEscape($_product->getName()) ?>" itemprop="image"/>
                            </a>
                            <div class="product-info">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <div class="product-info-bottom-left">
                                    <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped; ?>"
                                       itemprop="name"><?php echo $_product->getName() ?></a>
                                    <div
                                        class="collection-name"><?php echo $_product->getData('collection_name') ?></div>
                                </div>

                                <div
                                    class="product-info-bottom-right <?php $productprice = $this->getPriceHtml($_product, true);
                                    if (strpos($productprice, 'minimal-price-link') !== false) {
                                        echo 'category-price';
                                    } ?>">
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                </div>
                            </div>
                        </div>

                    </li>
                <?php endforeach ?>

            </ul>


        </div>
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>

<div class="category-products ">
    <?php /*?><?php echo $this->getToolbarHtml() ?><?php */ ?>
    <?php // List mode ?>

    <?php if ($this->getMode() != 'grid'): ?>
        <?php /*?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>" >
            <?php // Product Image ?>
            <div class="f-left">
                <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : //quick view button ?>
                <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' data-fancybox-group="gallery" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('quick view')?></a>
                <?php endif; ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
                    <?php
                    $_product->load('media_gallery');
                    $back_img = $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                    if ( $back_img ) {
                        echo '<img class="back_img" src="'. $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($listX, $listY).'" data-srcX2="'. $this->helper('catalog/image')->init($_product, 'small_image')->resize($listX*2, $listY*2) .'" width="'.$listX.'" height="'.$listY.'" alt="'.$this->htmlEscape($_product->getName()).'" />';
                    }
                    ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($listX, $listY); ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($listX*2, $listY*2); ?>" width="<?php echo $listX ?>" height="<?php echo $listY ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
            </div>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div class="price-container clearfix">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->getRatingSummary()){ echo $this->getReviewsSummaryHtml($_product); } ?>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <div class="button-container">
                        <?php if($_product->isSaleable()): ?>
                            <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>
                                <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                <p><a href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart ajax-cart btn-add-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span></span><?php echo $this->__('Add to Cart') ?></a></p>
                                <?php } else { ?>
                                <p><a href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart show-options btn-add-cart" data-id="<?php echo $_product->getId(); ?>"><span></span><?php echo $this->__('Add to Cart') ?></a></p>
                                <?php }  ?>
                            <?php else: ?>
                            <p><a href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart btn-add-cart"><span></span><?php echo $this->__('Add to Cart') ?></a></p>
                            <?php endif; ?>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>

                    <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId()?>'><img src='<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>'/></span>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <?php */ ?>
    <?php else: ?>

        <?php // Grid Mode ?>
        <?php /*?>
    <?php
    $_collectionSize = $_productCollection->count();

    $pageLayout = $this->getLayout()->getBlock('root')->getTemplate();
    if ( strpos($pageLayout, '2columns') ) {
        $grid_class = 'two_columns_' . Mage::getStoreConfig('shoppersettings/catalog/grid_columns_2col');
    } else {
        $grid_class = 'one_column_' . Mage::getStoreConfig('shoppersettings/catalog/grid_columns_1col');
    }
    $imgX = 252;
    $imgY = $helper->calculateHeight($imgX);
    ?>
     <ul class="products-grid <?php echo $grid_class; ?>">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <li class="item" itemscope itemtype="http://schema.org/Product">

            <div class="regular abcdef">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image" itemprop="url">
                    <?php $stockItem = $_product->getStockItem(); ?>
                    <?php if (!$stockItem->getIsInStock()): ?>
                         <div class="out-of-stock-label">Épuisé</div>
                    <?php endif; ?>
                    <div class="featured-product-label"><?php echo $_product->getData('featured_product') ?></div>
                    <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>

                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" itemprop="image" />
                </a>
               <div class="product-info">
                    <div class="button-container">
                        <?php if($_product->isSaleable()): ?>
                            <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>
                                <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php } else { ?>
                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php }  ?>
                            <?php else: ?>
                                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                            <?php endif; ?>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <div class="product-info-bottom-left">
                       <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" itemprop="name"><?php echo $_product->getName() ?></a>
                       <div class="collection-name"><?php echo $_product->getData('collection_name') ?></div>
                    </div>
                    <div class="product-info-bottom-right">
                       <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                </div>
            </div>

            <div class="hover">
                <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : //quick view button ?>
                    <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' data-fancybox-group="gallery" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('quick view')?></a>
                <?php endif; ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                    <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
                    <?php $stockItem = $_product->getStockItem(); ?>
                    <?php if (!$stockItem->getIsInStock()): ?>
                         <div class="out-of-stock-label">Épuisé</div>
                    <?php endif; ?>
                    <div class="featured-product-label"><?php echo $_product->getData('featured_product') ?></div>
                    <?php
                    $_product->load('media_gallery');
                    $back_img = $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                    if ( $back_img ) : ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    <?php else : ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    <?php endif; ?>
                </a>

	            <?php if (Mage::getStoreConfig('sales/msrp/enabled')) :  ?>
		            <?php echo $this->getPriceHtml($_product, true);  ?>
	            <?php else : ?>
		            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
			            <?php echo $this->helper('shoppersettings/data')->priceFormat( $this->getPriceHtml($_product, true) ); ?>
		            </a>
	            <?php endif; ?>

                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                <?php if($_product->getRatingSummary()){ echo $this->getReviewsSummaryHtml($_product); } ?>
                <div class="button-container">
                    <?php if($_product->isSaleable()): ?>

                        <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>

                            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                            <?php } else { ?>
                                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                            <?php }  ?>

                        <?php else: ?>
                            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php endif; ?>

                    <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>

                <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId()?>'><img src='<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>'/></span>

            </div>

        </li>
        <?php endforeach ?>
    </ul><?php */ ?>
    <?php endif; ?>

    <?php /*?><div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div><?php */ ?>


    <?php endif; ?>
